version: '3.9'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: license_mgmt_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: license_mgmt
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: license_mgmt_backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/license_mgmt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: license_mgmt_frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
